### ISSUE TITLE
Option to enable full validation on rules tree upload

### ISSUE THREAD

**Issue by lukaszczerpak** [akamai/cli-property#79] opened 2018-06-06 11:28 UTC
One of typical workflows is that the config is modified locally (not using Property Manager), uploaded via PAPI and then immediately activated. `update` command in the cli doesn't enforce full validation therefore it is possible that logical error (invalid attribute for instance) gets through quick json syntax check in PAPI, and then throws an error on activation without giving any further details.
Sort of workaround to check what causes the error is to retrieve the version using `retrieve` command where all errors and warnings are listed.
However it would be much more convenient to have an option in `update` command that forces full validation.

**Comment by joaquin-gimenez** [comment] 2019-02-08 11:27
Update command already uses the default params (validateRules=true, validateMode=full),
@lukaszczerpak could not reproduce the issue so it might have been a misunderstanding and agreed to close it

**Closed by joaquin-gimenez** 2019-02-08 11:27 UTC
