### ISSUE TITLE
P2: Add option to list products

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property#167] opened 2019-08-20 01:02 UTC
The property-manager CLI has already implemented this so you can probably just copy the code from https://github.com/akamai/cli-property-manager/blob/master/src/common/common_cli.js (see the listProducts function)

**Comment by dshafik** [comment] 2019-08-25 06:35
Closed, duplicate of #157

**Closed by dshafik** 2019-08-25 06:35 UTC
